export const search = {
    UPDATE: 'MOVIE/UPDATE_SEARCH'
}

export const genres = {
    GET__SUCCESS: 'MOVIE/GET_GENRES_SUCCESS',
    UPDATE: 'MOVIE/UPDATE-GENRE',
    // don't use:
    GET__FAILURE: 'MOVIE/GET_GENRES_FAILURE'
}

export const movieReviews = {
    REQUEST: 'MOVIE/REVIEWS_REQUEST',
    GET__SUCCESS: 'MOVIE/GET_REVIEWS_SUCCESS',
    GET__FAILURE: 'MOVIE/GET_REVIEWS_FAILURE'
}

export const movieDetails = {
    REQUEST: 'MOVIE/DETAIS_REQUEST',
    GET__SUCCESS: 'MOVIE/GET_DETAIL_SUCCESS',
    GET__FAILURE: 'MOVIE/GET_DETAIL_FAILURE'
}

export const collection = {
    REQUEST: 'MOVIE/COLLECTION_REQUEST',
    GET_SUCCESS: 'MOVIE/GET_COLLECTION_SUCCESS',
    GET_FAILURE: 'MOVIE/GET_COLLECTION_FAILURE'
}





