export const search = {
    UPDATE: 'SEARCH/UPDATE_SEARCH',
    TOGGLE__SEARCH_FIELD: 'SEARCH/TOGGLE__SEARCH_FIELD'
}

export const genres = {
    GET__SUCCESS: 'MOVIE/GET_GENRES_SUCCESS',
    UPDATE: 'MOVIE/UPDATE-GENRE',
    // don't use:
    GET__FAILURE: 'MOVIE/GET_GENRES_FAILURE'
}

export const movieReviews = {
    REQUEST: 'MOVIE/REVIEWS_REQUEST',
    GET__SUCCESS: 'MOVIE/GET_REVIEWS_SUCCESS',
    GET__FAILURE: 'MOVIE/GET_REVIEWS_FAILURE'
}

export const movieDetails = {
    REQUEST: 'MOVIE/DETAIS_REQUEST',
    GET__SUCCESS: 'MOVIE/GET_DETAIL_SUCCESS',
    GET__FAILURE: 'MOVIE/GET_DETAIL_FAILURE'
}

export const collection = {
    REQUEST: 'MOVIE/COLLECTION_REQUEST',
    GET_SUCCESS: 'MOVIE/GET_COLLECTION_SUCCESS',
    GET_FAILURE: 'MOVIE/GET_COLLECTION_FAILURE',
    CLEAR: 'MOVIE/CLEAR_COLLECTION'
}

export const similarMovies = {
    REQUEST: 'MOVIE/SIMILAR_MOVIES_REQUEST',
    GET_SUCCESS: 'MOVIE/GET_SIMILAR_MOVIES_SUCCESS',
    GET_FAILURE: 'MOVIE/GET_SIMILAR_MOVIES_FAILURE',
}

export const movieCredits = {
    REQUEST: 'MOVIE/CREDITS_REQUEST',
    GET_SUCCESS: 'MOVIE/GET_CREDITS_SUCCESS',
    GET_FAILURE: 'MOVIE/GET_CREDITS_FAILURE',
}

export const movieKeywords = {
    REQUEST: 'MOVIE/KEYWORDS_REQUEST',
    GET_SUCCESS: 'MOVIE/GET_KEYWORDS_SUCCESS',
    GET_FAILURE: 'MOVIE/GET_KEYWORDS_FAILURE',
}

export const searchMovies  = {
    REQUEST: 'SEARCH/REQUEST_MOVIES',
    GET_SUCCESS: 'SEARCH/GET_MOVIES_SUCCESS',
    GET_FAILURE: 'SEARCH/GET_MOVIES_FAILURE',
    CLEAR: 'SEARCH/CLEAR_MOVIES',
    UPDATE: 'SEARCH/MOVIES_UPDATE'
}

export const searchPeople = {
    REQUEST: 'SEARCH/REQUEST_PEOPLE',
    GET_SUCCESS: 'SEARCH/GET_PEOPLE_SUCCESS',
    GET_FAILURE: 'SEARCH/GET_PEOPLE_FAILURE',
    CLEAR: 'SEARCH/CLEAR_PEOPLE',
    UPDATE: 'SEARCH/PEOPLE_UPDATE'
}

export const people = {
    GET_DETAILS_SUCCESS: 'PEOPLE/GET_DETAILS_SUCCESS',
    GET_DETAILS_FAILURE: 'PEOPLE/GET_DETAILS_FAILURE',
    CLEAR: 'PEOPLE/CLEAR_PEOPLE_DETAIL'
}

export const movies = {
    SET_CURRENT_PAGE: 'MOVIES/SET_CURRENT_PAGE',
    SET_CURRENT_SORT_OPTION: 'MOVIES_SET_CURRENT_SORT_OPTION'
}